#define add 1
#define alter 2
#define column 3
#define comma 4
#define create 5 
#define data_type 6
#define delete 7 
#define dot 8
#define drop 9
#define equal 10 
#define from 11
#define identifier 12
#define in 13
#define insert 14
#define integer 15
#define into 16
#define key 17
#define left_parenthesis 18
#define not 19
#define null 20
#define primary 21
#define quote 22
#define right_parenthesis 23
#define select 24
#define semi_colon 25 
#define set 26
#define table 27
#define update 28
#define values 29
#define where 30